### ISSUE TITLE
pull more then 1000 profiles

### ISSUE THREAD

**Issue by mocerinoj** [tpitale/legato#118] opened 2016-03-21 20:29 UTC
I have a very old Google Analytics account that has over 1500+ profiles within in (I know they currently don't allow this many but I guess we are grandfathered in).  It appears `ga.profiles` only grabs the first 1000 results.  I assume the actually GA API call for this returns a next page of some sort.  Is there any support with Legato for getting the next page or all the profiles?

    ga = Legato::User.new(access_token)
    irb(main):086:0> ga.profiles.count
    1000

**Comment by tpitale** [comment] 2016-03-21 22:53
Duplicate of https://github.com/tpitale/legato/issues/12

**Closed by tpitale** 2016-03-21 22:53 UTC
